
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fygjsjpfpjljbssvyvpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Z2pzanBmcGpsamJzc3Z5dnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDAxMTQsImV4cCI6MjA1ODgxNjExNH0.x2QHYgz3mncqLghBG_cSN2WxrS80RFnwZJfZJM28uCY";

// Use custom SupabaseClient type to handle our database schema
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
